# GitHub action to automate the export of schematics, board production files
# from the KiCad files
# https://github.com/marketplace/actions/kicad-exports

name: kicad-exports

on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
    - '.github/workflows/kicad-exports.yml'
    - 'hardware/docs.kibot.yaml'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '.github/workflows/kicad-exports.yml'
      - 'hardware/docs.kibot.yaml'

jobs:
  baseboard_4slots:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nerdyscout/kicad-exports@v2.2
      with:
      # Required - kibot config file
        config: hardware/docs.kibot.yaml
      # optional - prefix to output defined in config
        dir: hardware
      # optional - schematic file
        schema: 'hardware/baseboard_4slots/*.sch'
      # optional - PCB design file
        board: 'hardware/baseboard_4slots/*.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: hardware
        path: hardware

  ioboard_2ports_rdm_isolated:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nerdyscout/kicad-exports@v2.2
      with:
      # Required - kibot config file
        config: hardware/docs.kibot.yaml
      # optional - prefix to output defined in config
        dir: hardware
      # optional - schematic file
        schema: 'hardware/ioboard_2ports_rdm_isolated/*.sch'
      # optional - PCB design file
        board: 'hardware/ioboard_2ports_rdm_isolated/*.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: hardware
        path: hardware

  ioboard_2ports_rdm_unisolated:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nerdyscout/kicad-exports@v2.2
      with:
      # Required - kibot config file
        config: hardware/docs.kibot.yaml
      # optional - prefix to output defined in config
        dir: hardware
      # optional - schematic file
        schema: 'hardware/ioboard_2ports_rdm_unisolated/*.sch'
      # optional - PCB design file
        board: 'hardware/ioboard_2ports_rdm_unisolated/*.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: hardware
        path: hardware

  ioboard_4ports_isolated:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nerdyscout/kicad-exports@v2.2
      with:
      # Required - kibot config file
        config: hardware/docs.kibot.yaml
      # optional - prefix to output defined in config
        dir: hardware
      # optional - schematic file
        schema: 'hardware/ioboard_4ports_isolated/*.sch'
      # optional - PCB design file
        board: 'hardware/ioboard_4ports_isolated/*.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: hardware
        path: hardware

  ioboard_4ports_unisolated:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nerdyscout/kicad-exports@v2.2
      with:
      # Required - kibot config file
        config: hardware/docs.kibot.yaml
      # optional - prefix to output defined in config
        dir: hardware
      # optional - schematic file
        schema: 'hardware/ioboard_4ports_unisolated/*.sch'
      # optional - PCB design file
        board: 'hardware/ioboard_4ports_unisolated/*.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: hardware
        path: hardware
